### ISSUE TITLE
get_landmarks.py issue

### ISSUE THREAD

**Issue by boomberung** [Shade5/FaceFitting#1]
When I run get_landmarks.py i get this issue:
Traceback (most recent call last):
  File "get_landmarks.py", line 23, in <module>
    bfm = MorphabelModel('models/BFM.mat')
  File "/home/computers/projects/FaceFitting/MorphabelModel.py", line 10, in __init__
    self.load(model_path)
  File "/home/computers/projects/FaceFitting/MorphabelModel.py", line 23, in load
    model = scipy.io.loadmat(model_path)['model'][0, 0]
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio.py", line 217, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/mio.py", line 72, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/usr/local/lib/python3.6/dist-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 50, 5

**Comment by Shade5** [comment]
Try this? https://github.com/scipy/scipy/issues/1845

**Comment by Leong1230** [comment]
Are you using Windows system? It is better not to use the .mat file provided in the download file, but generate it following https://github.com/YadiraF/face3d/tree/master/examples.

**Comment by fashionguy** [comment]
@Leong1230 right
